### ISSUE TITLE
User Story 1: List of all Locations

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/capestone-project-hungryOar#1]
## Value Proposition

**As a** hungry oarsman/woman
**I want** to see a list of cafes and restaurants by the water in Hamburg
**so that** I can decide where I can eat and drink without leaving the boat.
​

## Description

![Unbenannt-2023-06-30-1011](https://github.com/AlexDernov/Hungry-Oar-App/assets/127208943/7a6bf571-b8d7-4e02-9f22-a09d0cfa3133)
​

## Acceptance Criteria

- [x]  All locations are displayed as a list 👁️
- [x]  Listitem has the same height as content 
- [x]  Each locations's image is displayed 👁️
- [x]  Each locations's title is displayed 👁️
- [x]  Each locations's address is displayed 👁️

## Tasks

- [x]  Open  new branch
- [x]  Create db/models/Location
- [x]  Create db/connect
- [x]  Create a handler function with "if (request.method === "GET")"
- [x]  Fetch all locations data from MongoDB Atlas using SWR State, so that location are available on all previous pages
- [x]  Create the page pages/locations/index that renders the LocationsList component
- [x]  Create the component LocationsList to render a list.
- [x]  Style the LocationsList component
- [x]  All acceptance criteria marked with 👁️ are covered by component testing

## Complexity

M

**Comment by AlexDernov** [comment]
The title "Locations" comes later with Layout.
