### ISSUE TITLE
User Story 7: Favorites

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/capestone-project-hungryOar#13]
## Value Proposition

**As a** hungry oarsman/woman 
**I want to** mark locations as favorites
**so that** I can find them easier. 
​

## Description

​
![Favor](https://github.com/AlexDernov/capestone-project-hungryOar/assets/127208943/98efdd33-7b0a-400b-b556-f0db1817ef3d)

## Acceptance Criteria

- [ ] The favorite-button is displayed in each entry in the list view 
- [ ] The favorite-button is displayed in the details view 
- [ ] Clicking the favorite-button on a non-favorite location saves it as a favorite 
- [ ] Clicking the favorite-button on a favorite location removes it from favorites 
- [ ] A navigation link labeled "Favorites" is displayed 
- [ ] Clicking the "Favorites" shows the FavoritesPage
- [ ] All favorite locations are displayed as a list 
- [ ] Each location's image is displayed 
- [ ] Each location's name is displayed 
- [ ] Each location's address is displayed 
- [ ] Each location is displayed with active favorite-button 
- [ ] All favorite flags added to locations are persisted across browser reloads
- [ ] Marker on the Map change color if the location ist favorite location
      ​

## Tasks

- [ ] Create an additional state locationsInfo to save further information for locations
- [ ] Make the locationsInfo state globally available for all pages
- [ ] Store the favorite flag in the locationsInfo
- [ ] Reference locations by id in the additional state
- [ ] Create the component FavoriteButton
- [ ] FavoriteButton props: isFavorite, onToggleFavorite
- [ ] Render the FavoriteButton component in the LocationPreview and LocationDetails component
- [ ] Create the page pages/favorites that renders the LocationsList component
- [ ] Use data from the locationsInfo state to filter for all favorite locations
- [ ] Pass the list of all favorite locations via prop to the LocationsList component
- [ ] Install the package use-local-storage-state
- [ ] Use the useLocalStorageState hook to store the locationsInfo state
​

## Complexity

L

**Comment by Charlotte-Ketteler** [comment]
Very detailed User Story! LGTM! :)
