### ISSUE TITLE
Map marker filter

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/capestone-project-hungryOar#15]
## Value Proposition

**As a** hungry oarsmen/women
**I want to** be able to filter locations on the map 
**so that** I could have a better overview
​

## Description

![Filter](https://github.com/AlexDernov/capestone-project-hungryOar/assets/127208943/2876acef-df8f-465c-aa84-042ff92d4b3e)

## Acceptance Criteria

- [ ] Тhe section for filtering is displayed 
- [ ] Displays filtering by boat rental availability (radio button)
- [ ] Clicking the radio button filters markers on the map at once
- [ ] Displays filtering by menu/location type (check button)
- [ ] "Filter" button is displayed
- [ ] Clicking the "Filter" button  filters markers on the map
      ​

## Tasks

- [ ] Create Filter component with radio and check buttons
- [ ] Create filterVerleih and filterMenu functions
- [ ] Implementation of filtering logic into the created component and functions
      ​

## Complexity

M

**Comment by AlexDernov** [comment]
A button to show and hide the section for filtering was also added.
