### ISSUE TITLE
User Story 9: Log in 

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/capestone-project-hungryOar#17]
## Value Proposition

**As an** admin/user 
**I want to**  log in
**so that** I can see same more functions of the App. 
​

## Description

![login](https://github.com/AlexDernov/capestone-project-hungryOar/assets/127208943/7f212d74-e2a2-4de8-8486-1dc381ea2d59)

## Acceptance Criteria

- [ ] Log in button is displayed.
- [ ] Clicking log in button switches to the registration page
- [ ] Log in as an admin allows you to edit locations on detailed pages
- [ ] Log in as a user allows you to see an "Add location" button (functioning will be added in the next user story)
      ​

## Tasks(

- [ ] Create LoginPage
- [ ] Create LoginButton Component
- [ ] Install next-auth.js
- [ ] Creating page/api/[nextauth].js
- [ ] Put the "secrets" in .env.local
- [ ] Create constanten mit useSession()
- [ ] Generate Github (client) secret
- [ ] Create "Add location" button on the NavBar
- [ ] 

      ​

## Complexity

M (T-Shirt Sizes XS to XL)

**Comment by Charlotte-Ketteler** [comment]
LGTM. :)
