### ISSUE TITLE
User Story 10: Add Location/ send a message

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/capestone-project-hungryOar#18]
## Value Proposition

**As a** user 
**I want to** be able to suggest a new location and/or write a message to the admin
**so that** I would be able to make the app better. 
​

## Description

![Add:edit](https://github.com/AlexDernov/capestone-project-hungryOar/assets/127208943/a4e187c7-4fa3-4dd4-8390-0983b8c53fa4)

## Acceptance Criteria

- [ ] Clicking "Add" button switches to the AddPage
- [ ] Input fields "name of location", "address", "opening hours", "which boats can be rented" are displayed
- [ ] Check buttons to select menu type are displayed
- [ ] Radio buttons to select the possibility of renting boats are displayed
- [ ] Loading an image is possible
- [ ] "Save" button is displayed
- [ ] "Cancel" button is displayed
- [ ] Clicking the "Save" button saved the data in the locations collection on MongoDB 
- [ ] Clicking the "Cancel" button switches to the Homepage
- [ ] The uploaded image is saved on Cloudinary, and its address in the database collection
- [ ]  Input field "wright us a message" is displayed
- [ ]  "Sand" button is displayed
- [ ] Clicking the "Save" button saved the data in the locations collection on MongoDB 
      ​

## Tasks

- [ ] Create an AddLocation component, that renders two forms
- [ ] Create AddLocationForm and AddMessageForm components
- [ ] Create a new collection "Messages" on Mongo DB
- [ ] Create db model "messages"
- [ ] 
​

## Complexity

M (T-Shirt Sizes XS to XL)
