### ISSUE TITLE
User Story 2: Homepage with locations map

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/capestone-project-hungryOar#2]
## Value Proposition

**As a** hungry oarsman/woman
**I want to** to see a map at the homepage  
**so that** I can see where the locations are.
​

## Description

![homepage](https://github.com/AlexDernov/Hungry-Oar-App/assets/127208943/6ab0c52f-7201-4911-b2a6-b9abdf33693a)​

## Acceptance Criteria

- [ ] Title of the App is displayed and looks good
- [ ] Description of the App is displayed and looks good
- [ ] Map with all locations on it is displayed and looks good
      ​
## Tasks

- [ ] Open new branch 
- [ ] At the page pages/index: create the function HomePage and have it render only the Map component, Title and the description of the App.
- [ ] Create the component Map
- [ ] Create a map image with all locations from the list on it.
- [ ] Style the map component and the homepage
      ​

## Complexity

S

**Comment by NicoleHoerner** [comment]
✅ Title is there,
✅ Description of the App is displayed and
✅ I can see the map with locations (I can even click on the map and get to the list😀)
For mobile screen it looks good to me as well. 
But should we make it responsive (for all devices)? (It is just a hint and question in general?)
