### ISSUE TITLE
User Story 11: Admin mode (review, editing and take over of suggested location and messages) 

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/capestone-project-hungryOar#20]
## Value Proposition

**As an**  administrator  
**I want** to see all the suggested locations listed,  
**so that** I can edit them and move them to the main list if I wish. 
​

## Description

... (Wireframe, scribble, design)
​

## Acceptance Criteria

- [ ] "New locations" link on the NavBar is displayed
- [ ] Clicking "New locations" switches to the NewLocationsPage
- [ ] Suggested locations are displayed as a list
- [ ] Each list item (suggested location) has an "Edit" and "Take over" buttons
- [ ] Clicking on "Edit" button allows to edit the suggestion
- [ ] Clicking on "Take over" button allows to take over the suggestion in the main list of location, so that the suggested location becomes visible in the LocationsList of the App.
- [ ] "Messages" link on the NavBar is displayed
- [ ] Clicking "Messages" switches to the MessagesPage
- [ ] Messages are displayed as a list
- [ ] Each list item (message) has a "Delete" button
- [ ] Clicking on "Delete" button deletes a message from the list and from the MongoDB

     
## Tasks

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, testing
- [ ] ...
      ​

## Complexity

M (T-Shirt Sizes XS to XL)

**Comment by Charlotte-Ketteler** [comment]
This is a detailed and well explained US. Very good!
