### ISSUE TITLE
User Story 12: Server side rendering

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/capestone-project-hungryOar#23]
## Value Proposition

**As an** app admin, 
**I want** the "secret" information not to be available to users
** to** secure the application from outside interference.
​

## Description

-
​

## Acceptance Criteria

- [ ]All "secret" information is rendered on the server side.

      ​

## Tasks

- [ ] Create new branch
- [ ] Client side rendering is replaced by the server side rendering (with getSideProps)

      ​

## Complexity

S

**Comment by AlexDernov** [comment]
Admin data (session.user === "XY") and API-Routers

**Comment by ahohnsen** [comment]
Hey Alex,

I suggest to be a bit more specific in your Acceptance Criteria. Theoretically, your user story should be written in a way that anyone can understand and implement it. 🙂
