### ISSUE TITLE
User Story 3: Layout and Navigation Bar

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/capestone-project-hungryOar#3]
## Value Proposition

**As a** hungry oarsman/woman
**I want to** be able to switch between the Homepage (with a map) and list view  
**so that** I can navigate the app easier.
​

## Description

.![layout and Navigation](https://github.com/AlexDernov/Hungry-Oar-App/assets/127208943/ee1d2df6-f662-4668-855e-7d5c9bb64e76)
​

## Acceptance Criteria

- [ ] A navigation link mit icon "List" is displayed 
- [ ] A navigation link mit icon "Map"  is displayed 
- [ ] A navigation link "<- Back" is displayed
- [ ] Clicking "Map"  shows the HomePage
- [ ] Clicking "List"  shows the Locations Page
- [ ] Clicking "<-Back" shows the previous Page
- [ ] Clicking the map shows the Locations Page
      ​

## Tasks

- [ ] Create the component Navigation that renders all navigation links
- [ ] Create the component Layout that renders the Navigation component
- [ ] Apply the Layout component in pages/_app
- [ ] Style the Layout und Navigation components
      ​

## Complexity

S

**Comment by AlexDernov** [comment]
I did not implement the navigation link "<- Back" on purpose, because I noticed that there is no need for it - its function is implemented in the navigation bar. I also changed the location of the NavBar.
