### ISSUE TITLE
User Story 4: Location Details Page

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/capestone-project-hungryOar#4]
## Value Proposition

**As a** hungry oarsman/woman
**I want to** I want to be able to see the detail information about locations 
**so that** so that I can learn more about each location and decide where I want to eat/trink.​

## Description

![LocationDetails](https://github.com/AlexDernov/capstone-project-hungry-oar/assets/127208943/e4231a59-2197-423a-99e6-bf6643df7165)

​
## Acceptance Criteria

- [ ]  Clicking a location from the list shows the detail page
- [ ]  The location image is displayed 
- [ ]  The location name is displayed 
- [ ]  The location address is displayed 
- [ ]  The location opening hours are displayed 
- [ ]  The location menu type is displayed 
- [ ]  Information about the possibility of renting a boat on the spot is displayed 
- [ ]  A back-button is displayed 
- [ ]  Clicking the back-button shows the list view

      ​
## Tasks

- [ ] Create the component LocationDetails
- [ ] ArtPieceDetails props: bild, name, location, zeit, art, verleih
- [ ]  Create the page pages/locations/[id] that renders LocationDetails
- [ ]  Read the query parameter id from next/router
- [ ]  Use the id to find the location to display
- [ ] Style the details page und LocationDetails component
​

## Complexity

S
