### ISSUE TITLE
User Story 5: Notes for Locations

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/capestone-project-hungryOar#8]
## Value Proposition

**As a** hungry oarsman/woman
**I want to** write notes for each location 
**so that** I can save more Information about location

## Description

... (Wireframe, scribble, design)
​

## Acceptance Criteria

- [ ] The detail view has a list of notes for this art piece with the headline "Notes"
- [ ] Each note's text is displayed
- [ ] Each comment's date and time is displayed
- [ ] The detail view has an input field to write a comment
- [ ] The detail view has a submit button labeled "Save"
- [ ] After submitting the form, the note is appended to the list of notes
- [ ] After submitting the form, the note is saved in the corresponding document in MongoDB.
      ​

## Tasks

- [ ] Store comments per art piece in the artPiecesInfo state
- [ ] Add if (request.method === "POST") to the handler function in api/location/[id].js
- [ ] Create a NoteForm component with async handleSubmit function for updating the data.

## Complexity

M

**Comment by uwoch** [comment]
LGTM! You could add in the Acceptance Criteria how the delete function works, because you decribed the submitting and the editing. ;-)

**Comment by AlexDernov** [comment]
Styling of buttons comes later
