### ISSUE TITLE
User Story 6

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/capestone-project-hungryOar#9]
## Value Proposition

**As a** hungry oarsman/woman
**I want to** be able to delete the note
**so that** I don't have unnecessary information in the list of notes
​

## Description

... (Wireframe, scribble, design)
​

## Acceptance Criteria

- [ ] Delete button for each note is displayed
- [ ] Pressing the corresponding delete button, deletes the note from the list and from the database.
​

## Tasks

- [ ]  Create a new branch
- [ ]  Add a delete button so that it is visible for each note that appears in the list
- [ ]  Implement the logic for the button
- [ ]  Add some styling.
      ​

## Complexity

M (T-Shirt Sizes XS to XL)

**Comment by StanislavOlijnik** [comment]
Could you consider using a persona that aligns with the app's purpose instead of "hungry oarsman/woman"? For example, if it's a travel app, you could use a traveler persona.

but otherwise it looks good !

**Comment by AlexDernov** [comment]
No, it`s not a travel app.This is an app for hungry paddlers paddling the canals of Hamburg. From the name of the app "Hungry Oar" call these people hungry oarsman/woman. It's a conscious choice of name.
